# Generated by Django 4.2.27 on 2026-01-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, verbose_name='IP Address')),
                ('country_code', models.CharField(db_index=True, max_length=10, verbose_name='Country Code')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('visitor_type', models.CharField(db_index=True, help_text='GLOBAL or LOCAL', max_length=20, verbose_name='Visitor Type')),
                ('first_visit', models.DateTimeField(auto_now_add=True, verbose_name='First Visit')),
                ('last_visit', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Last Visit')),
                ('visit_count', models.PositiveIntegerField(default=1, verbose_name='Visit Count')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('device_type', models.CharField(blank=True, help_text='desktop, mobile, tablet', max_length=50, verbose_name='Device Type')),
                ('browser', models.CharField(blank=True, max_length=100, verbose_name='Browser')),
                ('browser_version', models.CharField(blank=True, max_length=50, verbose_name='Browser Version')),
                ('os', models.CharField(blank=True, max_length=100, verbose_name='Operating System')),
                ('os_version', models.CharField(blank=True, max_length=50, verbose_name='OS Version')),
                ('pages_viewed', models.PositiveIntegerField(default=1, verbose_name='Pages Viewed')),
                ('time_on_site', models.PositiveIntegerField(default=0, help_text='Total time in seconds', verbose_name='Time on Site')),
                ('bounce', models.BooleanField(default=False, help_text='Left after viewing only one page', verbose_name='Bounce')),
                ('submitted_form', models.BooleanField(db_index=True, default=False, verbose_name='Submitted Form')),
                ('form_type', models.CharField(blank=True, max_length=50, verbose_name='Form Type')),
                ('conversion_date', models.DateTimeField(blank=True, null=True, verbose_name='Conversion Date')),
                ('referrer_domain', models.CharField(blank=True, max_length=255, verbose_name='Referrer Domain')),
                ('utm_source', models.CharField(blank=True, max_length=100, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, max_length=100, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=100, verbose_name='UTM Campaign')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Geo Visitor',
                'verbose_name_plural': 'Geo Visitors',
                'db_table': 'geo_visitors',
                'ordering': ['-last_visit'],
                'indexes': [models.Index(fields=['ip_address'], name='geo_visitor_ip_addr_ebcb53_idx'), models.Index(fields=['country_code'], name='geo_visitor_country_ec9b57_idx'), models.Index(fields=['visitor_type'], name='geo_visitor_visitor_ef73e9_idx'), models.Index(fields=['-last_visit'], name='geo_visitor_last_vi_3a9a2d_idx')],
            },
        ),
    ]
