# Generated by Django 4.2.27 on 2026-01-08 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (English)')),
                ('title_tr', models.CharField(max_length=255, verbose_name='Title (Turkish)')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL Slug')),
                ('client_company', models.CharField(max_length=255, verbose_name='Client Company')),
                ('client_industry', models.CharField(max_length=100, verbose_name='Industry')),
                ('client_country', models.CharField(max_length=100, verbose_name='Country')),
                ('client_logo', models.URLField(blank=True, max_length=500, verbose_name='Client Logo URL')),
                ('case_type', models.CharField(choices=[('market_entry', 'Market Entry (Foreign to Turkey)'), ('export', 'Export (Turkey to Global)')], max_length=50, verbose_name='Case Type')),
                ('challenge_en', models.TextField(verbose_name='Challenge (English)')),
                ('challenge_tr', models.TextField(verbose_name='Challenge (Turkish)')),
                ('solution_en', models.TextField(verbose_name='Solution (English)')),
                ('solution_tr', models.TextField(verbose_name='Solution (Turkish)')),
                ('results_en', models.TextField(verbose_name='Results (English)')),
                ('results_tr', models.TextField(verbose_name='Results (Turkish)')),
                ('metric_1_label_en', models.CharField(blank=True, max_length=100, verbose_name='Metric 1 Label (EN)')),
                ('metric_1_label_tr', models.CharField(blank=True, max_length=100, verbose_name='Metric 1 Label (TR)')),
                ('metric_1_value', models.CharField(blank=True, max_length=50, verbose_name='Metric 1 Value')),
                ('metric_2_label_en', models.CharField(blank=True, max_length=100, verbose_name='Metric 2 Label (EN)')),
                ('metric_2_label_tr', models.CharField(blank=True, max_length=100, verbose_name='Metric 2 Label (TR)')),
                ('metric_2_value', models.CharField(blank=True, max_length=50, verbose_name='Metric 2 Value')),
                ('metric_3_label_en', models.CharField(blank=True, max_length=100, verbose_name='Metric 3 Label (EN)')),
                ('metric_3_label_tr', models.CharField(blank=True, max_length=100, verbose_name='Metric 3 Label (TR)')),
                ('metric_3_value', models.CharField(blank=True, max_length=50, verbose_name='Metric 3 Value')),
                ('testimonial_en', models.TextField(blank=True, verbose_name='Testimonial (English)')),
                ('testimonial_tr', models.TextField(blank=True, verbose_name='Testimonial (Turkish)')),
                ('testimonial_author', models.CharField(blank=True, max_length=255, verbose_name='Testimonial Author')),
                ('testimonial_position', models.CharField(blank=True, max_length=255, verbose_name='Author Position')),
                ('featured_image', models.URLField(blank=True, max_length=500, verbose_name='Featured Image URL')),
                ('meta_description_en', models.TextField(blank=True, max_length=160, verbose_name='Meta Description (EN)')),
                ('meta_description_tr', models.TextField(blank=True, max_length=160, verbose_name='Meta Description (TR)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20, verbose_name='Status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Case Study',
                'verbose_name_plural': 'Case Studies',
                'db_table': 'case_studies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'is_featured'], name='case_studie_status_5ebd0f_idx'), models.Index(fields=['case_type'], name='case_studie_case_ty_680d97_idx'), models.Index(fields=['slug'], name='case_studie_slug_94f095_idx')],
            },
        ),
    ]
