# Generated by Django 4.2.27 on 2026-01-08 06:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Company Name')),
                ('email', models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('inquiry_type', models.CharField(max_length=100, verbose_name='Inquiry Type')),
                ('inquiry_context', models.CharField(blank=True, help_text='Which page was form submitted from', max_length=50, verbose_name='Context')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
                ('source_page', models.CharField(blank=True, max_length=255, verbose_name='Source Page')),
                ('language', models.CharField(blank=True, max_length=10, verbose_name='Language')),
                ('visitor_type', models.CharField(blank=True, max_length=20, verbose_name='Visitor Type')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('country_detected', models.CharField(blank=True, max_length=10, verbose_name='Country Detected')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('referrer_url', models.URLField(blank=True, max_length=500, verbose_name='Referrer')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('replied', 'Replied'), ('closed', 'Closed'), ('spam', 'Spam')], db_index=True, default='new', max_length=50, verbose_name='Status')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Internal Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Submitted At')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='Replied At')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'db_table': 'contact_submissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='contact_sub_status_88fb2c_idx'), models.Index(fields=['-created_at'], name='contact_sub_created_022c3a_idx'), models.Index(fields=['email'], name='contact_sub_email_903821_idx'), models.Index(fields=['inquiry_type'], name='contact_sub_inquiry_dd3948_idx')],
            },
        ),
    ]
