# Generated by Django 4.2.27 on 2026-01-08 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Subscribed At')),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True, verbose_name='Unsubscribed At')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('source_page', models.CharField(blank=True, max_length=255, verbose_name='Source Page')),
            ],
            options={
                'verbose_name': 'Newsletter Subscription',
                'verbose_name_plural': 'Newsletter Subscriptions',
                'db_table': 'newsletter_subscriptions',
                'ordering': ['-subscribed_at'],
                'indexes': [models.Index(fields=['email'], name='newsletter__email_71b1f8_idx'), models.Index(fields=['-subscribed_at'], name='newsletter__subscri_5ee02a_idx'), models.Index(fields=['is_active'], name='newsletter__is_acti_9643c9_idx')],
            },
        ),
    ]
