// components/audit/AuditReportView.tsx
import React from 'react';
import { FileSearch, CheckCircle2, XCircle, Download, Info, AlertTriangle, ShieldCheck, ChevronRight } from 'lucide-react';
import { motion } from 'framer-motion';
import type { AuditIssue, HSRecommendation } from '../../services/AuditService';

interface AuditReportViewProps {
    issues: AuditIssue[];
    recommendations: HSRecommendation[];
    setIssues: (val: AuditIssue[]) => void;
    setRecommendations: (val: HSRecommendation[]) => void;
    setFiles: (val: File[]) => void;
    onClose?: () => void;
}

export const AuditReportView: React.FC<AuditReportViewProps> = ({ issues }) => {
    const criticalCount = issues.filter(i => i.severity === 'CRITICAL').length;
    const warningCount = issues.filter(i => i.severity === 'WARNING').length;
    const score = Math.max(0, 100 - (criticalCount * 20) - (warningCount * 10));

    return (
        <div className="bg-white rounded-[2.5rem] border border-slate-200 shadow-2xl overflow-hidden animate-in fade-in slide-in-from-bottom-8 duration-700">
            <div className="bg-navy p-10 text-white flex flex-col md:flex-row justify-between items-center gap-6 relative overflow-hidden">
                <div className="absolute top-0 right-0 w-64 h-64 bg-yellow/5 blur-3xl rounded-full translate-x-12 -translate-y-12"></div>
                <div className="relative z-10">
                    <h3 className="text-3xl font-black italic tracking-tighter flex items-center gap-4 uppercase leading-none">
                        <div className="bg-white/10 p-3 rounded-2xl">
                            <FileSearch size={32} className="text-yellow" />
                        </div>
                        Audit Report: #LX-2026-88
                    </h3>
                    <p className="text-sm text-blue-200 font-bold uppercase tracking-widest mt-4 opacity-70">Generated by DeepSeek-R1 Compliance Engine</p>
                </div>
                <button className="bg-white/5 hover:bg-white hover:text-navy px-8 py-4 rounded-2xl flex items-center gap-3 text-xs font-black uppercase tracking-[0.2em] transition-all border border-white/10 relative z-10 shadow-xl group">
                    <Download size={18} className="group-hover:translate-y-0.5 transition-transform" /> Save PDF Report
                </button>
            </div>

            <div className="p-10 lg:p-14">
                {/* Statistics Grid */}
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-12">
                    <div className="bg-emerald-50 border border-emerald-100 p-8 rounded-[2rem] flex items-center gap-6 group hover:bg-emerald-100 transition-all">
                        <div className="w-16 h-16 bg-emerald-500 text-white rounded-2xl flex items-center justify-center shadow-lg shadow-emerald-500/20">
                            <CheckCircle2 size={32} />
                        </div>
                        <div>
                            <p className="text-[10px] text-emerald-700 font-black uppercase tracking-widest mb-1">Compliance Score</p>
                            <p className="text-4xl font-black text-emerald-800 leading-none tracking-tighter">{score}%</p>
                        </div>
                    </div>
                    <div className={`p-8 rounded-[2rem] border flex items-center gap-6 transition-all ${criticalCount > 0 ? 'bg-red-50 border-red-100 hover:bg-red-100' : 'bg-slate-50 border-slate-100'}`}>
                        <div className={`w-16 h-16 rounded-2xl flex items-center justify-center shadow-lg ${criticalCount > 0 ? 'bg-red-600 text-white shadow-red-600/20' : 'bg-slate-200 text-slate-400'}`}>
                            <XCircle size={32} />
                        </div>
                        <div>
                            <p className={`text-[10px] font-black uppercase tracking-widest mb-1 ${criticalCount > 0 ? 'text-red-700' : 'text-slate-500'}`}>Critical Flags</p>
                            <p className={`text-4xl font-black leading-none tracking-tighter ${criticalCount > 0 ? 'text-red-800' : 'text-slate-300'}`}>{criticalCount} Issue{criticalCount !== 1 ? 's' : ''}</p>
                        </div>
                    </div>
                    <div className="bg-blue-50 border border-blue-100 p-8 rounded-[2rem] flex items-center gap-6 group hover:bg-blue-100 transition-all">
                        <div className="w-16 h-16 bg-blue-600 text-white rounded-2xl flex items-center justify-center shadow-lg shadow-blue-600/20">
                            <ShieldCheck size={32} />
                        </div>
                        <div>
                            <p className="text-[10px] text-blue-700 font-black uppercase tracking-widest mb-1">Verified Nodes</p>
                            <p className="text-4xl font-black text-blue-800 leading-none tracking-tighter">14</p>
                        </div>
                    </div>
                </div>

                {/* Audit Details */}
                <div className="space-y-6">
                    <div className="flex items-center gap-4 mb-4">
                        <h4 className="text-xl font-black text-navy uppercase italic tracking-tight">Identified Risks & Optimization</h4>
                        <div className="h-px flex-1 bg-slate-100"></div>
                    </div>

                    {issues.map((issue) => (
                        <motion.div
                            key={issue.id}
                            whileHover={{ x: 5 }}
                            className={`group border rounded-[2rem] p-8 transition-all ${issue.severity === 'CRITICAL' ? 'border-red-100 bg-red-50/20 hover:bg-red-50/40' :
                                issue.severity === 'WARNING' ? 'border-yellow-100 bg-yellow-50/20 hover:bg-yellow-50/40' :
                                    'border-blue-100 bg-blue-50/20 hover:bg-blue-50/40'
                                }`}
                        >
                            <div className="flex justify-between items-start mb-6">
                                <div className="flex items-center gap-3">
                                    <span className={`text-[9px] font-black px-4 py-1.5 rounded-full uppercase tracking-widest shadow-sm ${issue.severity === 'CRITICAL' ? 'bg-red-600 text-white' :
                                        issue.severity === 'WARNING' ? 'bg-yellow-500 text-white' : 'bg-blue-600 text-white'
                                        }`}>
                                        {issue.severity}
                                    </span>
                                    <span className="text-[10px] font-black text-slate-300 uppercase italic tracking-widest">Category: {issue.category}</span>
                                </div>
                                <div className="w-10 h-10 bg-white rounded-xl shadow-sm border border-slate-100 flex items-center justify-center text-slate-300 group-hover:text-navy transition-colors">
                                    <Info size={18} />
                                </div>
                            </div>

                            <h5 className="text-xl font-black text-navy mb-3 italic leading-tight">{issue.description}</h5>

                            <div className="mt-6 flex flex-col md:flex-row gap-4">
                                <div className="flex-1 bg-white border border-slate-100 p-6 rounded-3xl relative shadow-sm">
                                    <div className="absolute -top-3 left-6 px-3 bg-white text-[9px] font-black text-blue-600 uppercase tracking-widest border border-slate-50 rounded-full">
                                        AI Resolution Path
                                    </div>
                                    <p className="text-sm font-bold text-slate-600 leading-relaxed italic">
                                        "{issue.suggestion}"
                                    </p>
                                </div>
                                <button className="bg-navy text-white px-8 py-4 rounded-2xl font-black text-[10px] uppercase tracking-widest hover:bg-blue-600 transition-all flex items-center gap-2 shrink-0 self-end shadow-xl shadow-navy/10">
                                    Fix Discrepancy <ChevronRight size={14} />
                                </button>
                            </div>
                        </motion.div>
                    ))}
                </div>

                {/* Footer info */}
                <div className="mt-12 pt-8 border-t border-slate-50 flex flex-col md:flex-row justify-between items-center gap-4">
                    <div className="flex items-center gap-2 text-slate-300">
                        <AlertTriangle size={14} />
                        <span className="text-[10px] font-black uppercase tracking-[0.2em]">Risk Exposure: Minimal</span>
                    </div>
                    <p className="text-[10px] font-bold text-slate-400 italic">
                        This report is a digital audit conducted under L.O.X Protocol v8.2. © 2026 LOXTR
                    </p>
                </div>
            </div>
        </div>
    );
};
