# Generated by Django 4.2.27 on 2026-01-08 06:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('market_entry', 'Market Entry'), ('export_program', 'Export Program')], db_index=True, max_length=50, verbose_name='Application Type')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('contact_name', models.CharField(max_length=255, verbose_name='Contact Person')),
                ('email', models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('website_url', models.URLField(blank=True, max_length=500, verbose_name='Website')),
                ('product_category', models.CharField(max_length=100, verbose_name='Product Category')),
                ('product_description', models.TextField(verbose_name='Product Description')),
                ('current_markets', models.TextField(blank=True, help_text='Markets where you currently sell', verbose_name='Current Markets')),
                ('annual_production_capacity', models.CharField(blank=True, max_length=255, verbose_name='Annual Production Capacity')),
                ('target_markets', models.TextField(blank=True, help_text='Markets you want to enter', verbose_name='Target Markets')),
                ('certifications', models.TextField(blank=True, help_text='ISO, CE, TSE, etc.', verbose_name='Certifications')),
                ('export_experience_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='Export Experience (Years)')),
                ('company_profile_url', models.URLField(blank=True, max_length=500, verbose_name='Company Profile URL')),
                ('product_catalog_url', models.URLField(blank=True, max_length=500, verbose_name='Product Catalog URL')),
                ('certificates_url', models.URLField(blank=True, max_length=500, verbose_name='Certificates URL')),
                ('status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under Review'), ('meeting_scheduled', 'Meeting Scheduled'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], db_index=True, default='new', max_length=50, verbose_name='Status')),
                ('internal_notes', models.TextField(blank=True, help_text='Not visible to applicant', verbose_name='Internal Notes')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('visitor_type', models.CharField(blank=True, help_text='GLOBAL or LOCAL', max_length=20, verbose_name='Visitor Type')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('country_detected', models.CharField(blank=True, help_text='From GeoIP', max_length=10, verbose_name='Country Detected')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('referrer_url', models.URLField(blank=True, max_length=500, verbose_name='Referrer')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Submitted At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application_type', 'status'], name='application_applica_97cba4_idx'), models.Index(fields=['-created_at'], name='application_created_ffe3db_idx'), models.Index(fields=['email'], name='application_email_7bef0d_idx'), models.Index(fields=['country'], name='application_country_7ec771_idx')],
            },
        ),
    ]
