# Generated by Django 4.2.27 on 2026-01-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_path', models.CharField(db_index=True, help_text='e.g., /en/market-entry/', max_length=255, unique=True, verbose_name='Page Path')),
                ('page_type', models.CharField(blank=True, help_text='homepage, category, product, content', max_length=50, verbose_name='Page Type')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='Title (English)')),
                ('title_tr', models.CharField(blank=True, max_length=255, verbose_name='Title (Turkish)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_tr', models.TextField(blank=True, verbose_name='Description (Turkish)')),
                ('keywords_en', models.TextField(blank=True, help_text='Comma-separated', verbose_name='Keywords (English)')),
                ('keywords_tr', models.TextField(blank=True, help_text='Comma-separated', verbose_name='Keywords (Turkish)')),
                ('og_title_en', models.CharField(blank=True, max_length=255, verbose_name='OG Title (English)')),
                ('og_title_tr', models.CharField(blank=True, max_length=255, verbose_name='OG Title (Turkish)')),
                ('og_description_en', models.TextField(blank=True, verbose_name='OG Description (English)')),
                ('og_description_tr', models.TextField(blank=True, verbose_name='OG Description (Turkish)')),
                ('og_image', models.URLField(blank=True, max_length=500, verbose_name='OG Image URL')),
                ('og_type', models.CharField(default='website', max_length=50, verbose_name='OG Type')),
                ('twitter_card_type', models.CharField(default='summary_large_image', max_length=50, verbose_name='Twitter Card Type')),
                ('twitter_title_en', models.CharField(blank=True, max_length=255, verbose_name='Twitter Title (English)')),
                ('twitter_title_tr', models.CharField(blank=True, max_length=255, verbose_name='Twitter Title (Turkish)')),
                ('twitter_description_en', models.TextField(blank=True, verbose_name='Twitter Description (English)')),
                ('twitter_description_tr', models.TextField(blank=True, verbose_name='Twitter Description (Turkish)')),
                ('twitter_image', models.URLField(blank=True, max_length=500, verbose_name='Twitter Image URL')),
                ('schema_json', models.JSONField(blank=True, default=dict, help_text='Structured data for rich snippets', verbose_name='Schema.org JSON-LD')),
                ('robots_directive', models.CharField(default='index, follow', max_length=100, verbose_name='Robots Directive')),
                ('canonical_url', models.URLField(blank=True, max_length=500, verbose_name='Canonical URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Metadata',
                'verbose_name_plural': 'SEO Metadata',
                'db_table': 'seo_metadata',
                'ordering': ['page_path'],
                'indexes': [models.Index(fields=['page_path'], name='seo_metadat_page_pa_d19c85_idx'), models.Index(fields=['page_type'], name='seo_metadat_page_ty_854b80_idx')],
            },
        ),
    ]
