# Generated by Django 4.2.27 on 2026-01-08 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='LOXTR', max_length=255, verbose_name='Company Name')),
                ('company_tagline', models.CharField(default='Locate • Obtain • Xport', max_length=255, verbose_name='Tagline')),
                ('company_email', models.EmailField(default='info@loxtr.com', max_length=254, verbose_name='Email')),
                ('company_phone', models.CharField(default='+90 (212) XXX XX XX', max_length=50, verbose_name='Phone')),
                ('whatsapp_number', models.CharField(default='+90 5XX XXX XX XX', max_length=50, verbose_name='WhatsApp Number')),
                ('office_address_en', models.TextField(default='Istanbul, Turkey', verbose_name='Office Address (English)')),
                ('office_address_tr', models.TextField(default='İstanbul, Türkiye', verbose_name='Office Address (Turkish)')),
                ('working_hours_en', models.TextField(default='Monday - Friday: 9:00 AM - 6:00 PM', verbose_name='Working Hours (English)')),
                ('working_hours_tr', models.TextField(default='Pazartesi - Cuma: 09:00 - 18:00', verbose_name='Working Hours (Turkish)')),
                ('linkedin_url', models.URLField(default='https://linkedin.com/company/loxtrcom', max_length=500, verbose_name='LinkedIn URL')),
                ('instagram_url', models.URLField(default='https://instagram.com/loxtrcom', max_length=500, verbose_name='Instagram URL')),
                ('youtube_url', models.URLField(default='https://youtube.com/@loxtrcom', max_length=500, verbose_name='YouTube URL')),
                ('twitter_url', models.URLField(blank=True, max_length=500, verbose_name='Twitter/X URL')),
                ('facebook_url', models.URLField(blank=True, max_length=500, verbose_name='Facebook URL')),
                ('google_analytics_id', models.CharField(blank=True, help_text='e.g., G-XXXXXXXXXX', max_length=50, verbose_name='Google Analytics ID')),
                ('google_tag_manager_id', models.CharField(blank=True, help_text='e.g., GTM-XXXXXXX', max_length=50, verbose_name='Google Tag Manager ID')),
                ('google_site_verification', models.CharField(blank=True, max_length=100, verbose_name='Google Site Verification Code')),
                ('enable_newsletter', models.BooleanField(default=True, verbose_name='Enable Newsletter')),
                ('enable_whatsapp_button', models.BooleanField(default=True, verbose_name='Enable WhatsApp Button')),
                ('enable_live_chat', models.BooleanField(default=False, verbose_name='Enable Live Chat')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable to show maintenance page', verbose_name='Maintenance Mode')),
                ('maintenance_message_en', models.TextField(blank=True, verbose_name='Maintenance Message (English)')),
                ('maintenance_message_tr', models.TextField(blank=True, verbose_name='Maintenance Message (Turkish)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
                'db_table': 'site_settings',
            },
        ),
    ]
